# Generated by Django 3.1.4 on 2021-01-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_choice', models.CharField(choices=[('TWT', 'Twitter'), ('INS', 'Instagram'), ('TIK', 'TikTok'), ('FBK', 'Facebook'), ('YTB', 'Youtube'), ('LNE', 'LINE'), ('MIS', 'Other')], default='MIS', max_length=3)),
                ('link', models.URLField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Macy.user')),
            ],
        ),
    ]
