# Generated by Django 3.1.5 on 2021-02-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
