# Generated by Django 3.1.4 on 2021-01-28 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='id',
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='links',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
