# Generated by Django 3.1.4 on 2021-02-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(null=True, upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
