# Generated by Django 3.1.4 on 2021-01-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0002_auto_20210128_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
