# Generated by Django 3.1.4 on 2021-02-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0002_auto_20210212_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
