# Generated by Django 3.1.4 on 2021-01-28 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0003_auto_20210128_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
