# Generated by Django 3.1.4 on 2021-02-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0004_auto_20210128_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
