# Generated by Django 3.1.4 on 2021-02-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Macy', '0005_links_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
